"""multi-tenant organizations

Revision ID: f682848b9938
Revises: 53c261b65b43
Create Date: 2026-08-23 15:55:08.365898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f682848b9938'
down_revision: Union[str, None] = '53c261b65b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # Seed org default para dados existentes
    op.execute("INSERT INTO organizations (id, name, slug, is_active) VALUES (1, 'Default Organization', 'default', true) ON CONFLICT (id) DO NOTHING")
    op.execute("SELECT setval('organizations_id_seq', (SELECT MAX(id) FROM organizations))")
    op.add_column('apartments', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_apartments_organization_id'), 'apartments', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'apartments', 'organizations', ['organization_id'], ['id'])
    op.execute("UPDATE apartments SET organization_id = 1 WHERE organization_id IS NULL")
    op.add_column('notifications', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'organizations', ['organization_id'], ['id'])
    op.execute("UPDATE notifications SET organization_id = 1 WHERE organization_id IS NULL")
    op.add_column('products', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'])
    op.execute("UPDATE products SET organization_id = 1 WHERE organization_id IS NULL")
    op.add_column('schedule_tasks', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_schedule_tasks_organization_id'), 'schedule_tasks', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'schedule_tasks', 'organizations', ['organization_id'], ['id'])
    op.execute("UPDATE schedule_tasks SET organization_id = 1 WHERE organization_id IS NULL")
    op.add_column('schedules', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_schedules_organization_id'), 'schedules', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'schedules', 'organizations', ['organization_id'], ['id'])
    op.execute("UPDATE schedules SET organization_id = 1 WHERE organization_id IS NULL")
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.execute("UPDATE users SET organization_id = 1 WHERE organization_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_schedules_organization_id'), table_name='schedules')
    op.drop_column('schedules', 'organization_id')
    op.drop_constraint(None, 'schedule_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_tasks_organization_id'), table_name='schedule_tasks')
    op.drop_column('schedule_tasks', 'organization_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_column('products', 'organization_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_column('notifications', 'organization_id')
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.drop_index(op.f('ix_apartments_organization_id'), table_name='apartments')
    op.drop_column('apartments', 'organization_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###